### ISSUE TITLE
ZeroDivisionError when trying to copy data

### ISSUE THREAD

**Issue by B-Hartmann** [GuckLab/MPL-Data-Cast#12]
MPL data cast 0.2.2
Python 3.9.0
Windows 10

I tried copying an example folder with various files and one level of subfolders from my local machine to a network drive. This is what happened:

```bash
(mpl_data_cast) C:\Users\bhartma\Documents>mpldc cast -r RTDC ./20220405_BH_Messung_data_cast Z:\Members\Benedikt
Using recipe RTDC.
Traceback (most recent call last):
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\cli.py", line 79, in cast
    rp.cast(path_callback=path_callback, **kwargs)
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\recipe.py", line 62, in cast
    path_callback(path_list[0])
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\cli.py", line 102, in __call__
    rate = self.get_rate()
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\cli.py", line 109, in get_rate
    return self.size / 1024**2 / (time.monotonic() - self.time_start)
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bhartma\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bhartma\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\bhartma\.environments\mpl_data_cast\Scripts\mpldc.exe\__main__.py", line 7, in <module>
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\cli.py", line 79, in cast
    rp.cast(path_callback=path_callback, **kwargs)
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\cli.py", line 94, in __exit__
    rate = self.get_rate()
  File "c:\users\bhartma\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\cli.py", line 109, in get_rate
    return self.size / 1024**2 / (time.monotonic() - self.time_start)
ZeroDivisionError: float division by zero
```

I have a fresh environment with the following packages:
```bash
Package       Version
------------- ---------
click         8.1.2
colorama      0.4.4
dclab         0.40.0
h5py          3.6.0
mpl-data-cast 0.2.2
numpy         1.22.3
pip           22.0.4
PyQt6         6.2.3
PyQt6-Qt6     6.2.4
PyQt6-sip     13.2.1
scipy         1.8.0
setuptools    49.2.1
tifffile      2022.3.16
wheel         0.37.1
```

**Comment by paulmueller** [comment]
fixed in 0.2.3 (available on pypi in a minute)
