### ISSUE TITLE
version 0.4.0: no gui opening and error in cli 

### ISSUE THREAD

**Issue by felix-r** [GuckLab/MPL-Data-Cast#18]
Just upgraded on a lab PC via pip: `pip install --upgrade mpl_data_cast` and got version 0.4.0. I wanted to use the cli as usual but get an error now when I use `mpldc`:

```
(mpl_data_cast) C:\Users\labadmin>mpldc cast -r RTDC "D:\Experiments\20230112_Felix_artficial_cells_Eindhoven" "Y:\Data\RTDC\20230112_Felix_artficial_cells_Eindhoven"
Traceback (most recent call last):
  File "C:\Users\labadmin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\labadmin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\labadmin\.environments\mpl_data_cast\Scripts\mpldc.exe\__main__.py", line 4, in <module>
  File "C:\Users\labadmin\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\__init__.py", line 2, in <module>
    from .recipe import Recipe
  File "C:\Users\labadmin\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\recipe.py", line 11, in <module>
    from .util import hashfile
  File "C:\Users\labadmin\.environments\mpl_data_cast\lib\site-packages\mpl_data_cast\util.py", line 8, in <module>
    def hashfile(fname: str | pathlib.Path,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

The I tried to open the gui with `mpldc-gui` but nothing happened.

**Comment by paulmueller** [comment]
Sorry, the or `|` operator for typing was only introduced in Python 3.10. You are probably still on Python 3.9.

**Comment by paulmueller** [comment]
I "yanked" the 0.4.0 build from PyPI and added the 0.4.1 with the correct Python requirement. This should not happen again.
